In [1]:
import numpy as np

In [2]:
B2 = np.array([[1, 1],[2, 3]])
B2

array([[1, 1],
       [2, 3]])

In [3]:
M = np.linalg.inv(B2)
M

array([[ 3., -1.],
       [-2.,  1.]])

In [4]:
v1 = np.array([[4],[9]])

In [5]:
v2 = M@v1

In [6]:
v2

array([[3.],
       [1.]])